apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minidemo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: minidemo-storage-class

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minidemo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minidemo-storage-class